# Generated by Django 6.0.4 on 2026-10-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
