# Generated by Django 6.0.4 on 2026-09-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
    ]
